# Generated by Django 2.1.5 on 2019-02-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garbage_img', models.ImageField(blank=True, null=True, upload_to='qrcode/garbage/')),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
