# Generated by Django 2.1.5 on 2019-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garbage', '0002_auto_20190202_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garbage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
